### ISSUE TITLE
Clarify installation process

### ISSUE THREAD

**Issue by tobiase** [arteria/cmsplugin-contact-plus#22]
I had to create initial south migrations for Django 1.6.8.  with `python manage.py schemamigration cmsplugin_contact_plus --initial`. 

I'm new to Django. Maybe it's obvious for more experienced users, that they have to create the migrations, but it wasn't for me.

**Comment by kellito14** [comment]
I got everything installed but when I created a form and clicked submit , I got a connection refused error.

**Comment by walterrenner** [comment]
Hi @kellito14.

This issue is from 2014 and we have done some significant changes to cmsplugin-contact-plus. Would you please open a new Issue and provide more information and steps to reproduce your error.

Thanks.

**Comment by philippeowagner** [comment]
Please re-open if issue still persists.
