### ISSUE TITLE
"Match Captcha Field" missing in field dropdown. Can't find documentation regarding how to use SimpleMatchCaptcha

### ISSUE THREAD

**Issue by mrmikee** [arteria/cmsplugin-contact-plus#26]

**Comment by philippeowagner** [comment]
@mrmikee there was a problem while merging a PR. This should be fixed in d354606b84e804bc91d1048111d4de4bdc82bc47 . We pushed a [new version to PyPI](https://pypi.python.org/pypi/cmsplugin_contact_plus/1.2.2). Could you please give it a try?

**Comment by philippeowagner** [comment]
Closing this while assuming this works for you in the meantime.
