### ISSUE TITLE
Template setting does not work

### ISSUE THREAD

**Issue by jvamvas** [arteria/cmsplugin-contact-plus#33]
* Specify multiple templates, such as:
```python
CMSPLUGIN_CONTACT_PLUS_TEMPLATES = [
	('cmsplugin_contact_plus/contact.html', 'contact.html'),
	('cmsplugin_contact_plus/contact.html', 'contact2.html'),
]
```
* In the admin for a contact form, choose 'contact2.html'
* Save and reopen. The template setting was not saved.

**Comment by philippeowagner** [comment]
@jvamvas, probably because `cmsplugin_contact_plus/contact.html == cmsplugin_contact_plus/contact.html`

**Comment by jvamvas** [comment]
Correct.
