### ISSUE TITLE
How to setup this plugin

### ISSUE THREAD

**Issue by vaibhav-jain** [arteria/cmsplugin-contact-plus#38]
I am trying to setup this plugin in admin panel its models are listed but how do I add this to a page. I tried using this plugin templates but blank HTML is rendered ???

**Comment by jvamvas** [comment]
Please make sure you have followed the steps under https://github.com/arteria/cmsplugin-contact-plus#quickstart. Then, try to add the plugin to your CMS page as shown in this screenshot:

![screen shot 2016-09-07 at 09 11 44](https://cloud.githubusercontent.com/assets/5830820/18303043/5d87e61a-74db-11e6-9602-86a5e5a1849d.png)

If this is not working, please tell us more about your setup and about what is happening.

**Comment by vaibhav-jain** [comment]
@jvamvas Got it thanks
