### ISSUE TITLE
django-inline-ordering does not work

### ISSUE THREAD

**Issue by rfleschenberg** [arteria/cmsplugin-contact-plus#44]
It seems that cmsplugin-contact-plus depends on django-inline-ordering. The user should add `django-inline-ordering` to INSTALLED_APPS, but this is not documented. Easy fix, add this to the README.

However, with `inline-ordering` in INSTALLED_APPS, I am running into another problem:

```
Uncaught TypeError: InlineOrdering.jQuery(...).sortable is not a function
```

The last commit in https://github.com/centralniak/django-inline-ordering is from 2013. Maybe it's time to replace that dependency?

**Comment by jvamvas** [comment]
Thank you for pointing this out, @rfleschenberg. With v1.3.5, we have replaced django-inline-ordering with https://github.com/iambrandontaylor/django-admin-sortable.

Please note the upgrading instruction on https://github.com/arteria/cmsplugin-contact-plus/releases/tag/v1.3.5
